#!/usr/bin/env python3
import typer

# TYPER IMPORTS
from cli import certificate
from cli import config
from cli import database

# internal imports
from cli import internal_classes as IC


""" Code below is responsible for CLI """
app = typer.Typer(context_settings=dict(max_content_width=800))
app.add_typer(certificate.app, name="certificate", help="SSL Certificate related operations")
app.add_typer(config.app, name="config", help="HAProxy config file related operations")
app.add_typer(database.app, name="database", help="Manipulate the database")


@app.command()
def version():
    """
    Print out the version number and exit
    """  
    print("HosterRed Proxy: v0.1")

if __name__ == "__main__":
    app()